Makefile: better run of tests (still not ideal :)

diff --git a/experiments/fstorder/Makefile b/experiments/fstorder/Makefile
--- a/experiments/fstorder/Makefile
+++ b/experiments/fstorder/Makefile
@@ -17,4 +17,13 @@ clean:
 	@$(OCAMLBUILD) $@
 
 test:
-	PATH=_build:$$PATH . tests.itarget
+	for test in `cat tests.itarget`; do \
+		echo "* TEST: $$test"; \
+		_build/$$test; \
+		STATUS=$$?; \
+		if [ $$STATUS != 0 ]; then \
+			echo "* FAIL $$test"; \
+			exit $$STATUS; \
+		fi; \
+		echo "* SUCCESS: $$test"; \
+	done
